platform :ios, '11.0'

target 'Example' do
  use_frameworks!
end

target 'ExampleAPI' do
  use_frameworks!
  
  pod 'Alamofire'
  pod 'ApiClient', :path => "../"

  target 'ExampleAPITests' do
    inherit! :search_paths
  end
end