name: Release

on: 
  release:
    types:
      - published

jobs:
  release:
    name: Make CocoaPods release
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.app/Contents/Developer
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push Apexy.podspec --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}