name: Test
on: 
  # Trigger the workflow on push or pull request,
  # for all branches, but never trigger on new tags
  push:
    branches:
      - '**' 
    tags-ignore:
      - '**' 
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      - name: Build and test
        run: swift test --enable-code-coverage --disable-automatic-resolution
